export const PPT_STEPS = [
  { id: 1, icon: '🧹', titleKey: 'ppt_step1_t', descKey: 'ppt_step1_d' },
  { id: 2, icon: '🖼️', titleKey: 'ppt_step2_t', descKey: 'ppt_step2_d' },
  { id: 3, icon: '📑', titleKey: 'ppt_step3_t', descKey: 'ppt_step3_d' },
  { id: 4, icon: '📊', titleKey: 'ppt_step4_t', descKey: 'ppt_step4_d', hasScale: true },
  { id: 5, icon: '📦', titleKey: 'ppt_step5_t', descKey: 'ppt_step5_d' },
  { id: 6, icon: '🎉', titleKey: 'ppt_step6_t', descKey: 'ppt_step6_d', isFinal: true },
] as const;

export const PPT_I18N = {
  zh: {
    ppt_tips_title: '💕 导出说明：',
    ppt_tip_1: '⚠️ 为防止破坏源文件，必须创建当前Page的副本，名称中必须包含"副本" 或 "copy"。',
    ppt_tip_2: '⚠️ 混合路径、蒙版、模糊、特殊形状、曲线、折线等复杂图层PPT无法识别，无法在PPT中编辑，请各自编组重命名为"p_img"。',
    ppt_tip_3: '图片仅导出占位符，请从资源包中手动替换。',
    ppt_tip_4: '经过测试，1920x1080 画板对应 PPT 16:9 画布，导出时建议勾选缩小 0.5 倍，避免 PPT 过大。',
    ppt_tip_5: '重置按钮只重置插件，复原设计稿需要使用 Ctrl+Z 。',
    ppt_btn_auto: '🚀 一键自动导出 PPT',
    ppt_btn_manual: '📦 没收到？点此手动下载',
    ppt_btn_reset: '🌀 重置',
    ppt_step1_t: '1. 全局清洗',
    ppt_step1_d: '解锁图层、移除隐藏项、解绑实例',
    ppt_step2_t: '2. 图标图形栅格化',
    ppt_step2_d: '将复杂矢量图形和 p_img 图层转换为 PNG 素材',
    ppt_step3_t: '3. 深度扁平化',
    ppt_step3_d: '消除所有分组嵌套和不可见Frame，修复遮挡',
    ppt_step4_t: '4. 生成 PPT 结构',
    ppt_step4_d: '提取布局信息，生成 .pptx 文件',
    ppt_step4_scale: '缩放至 960x540，建议勾选',
    ppt_step5_t: '5. 导出资源包',
    ppt_step5_d: '打包生成 PPT 和图片资源 (.zip)',
    ppt_step6_t: '全部完成',
    ppt_step6_d: '文件已生成完成，请下载',
    ppt_stat_wait: '等待执行',
    ppt_stat_done: '✅ 执行成功',
    ppt_btn_next: '下一步 →',
    ppt_btn_done: '已完成',
    ppt_btn_run: '分步执行 STEP ',
    ppt_confirm_auto: '⚠️ 确定要全自动执行吗？\n请确保当前是【副本】页面，且已选中要导出的画板。',
    ppt_confirm_reset: '确定要重新开始吗？',
    ppt_no_data: '没有数据',
    ppt_loading_analyze: '正在分析设计稿结构...',
    ppt_loading_parse: '图层较多时耗时较长，请保持耐心...',
  },
  en: {
    ppt_tips_title: '💕 Export Tips:',
    ppt_tip_1: '⚠️ Create a copy of the page first. Name must include "copy".',
    ppt_tip_2: '⚠️ Complex layers (masks, blur, curves) should be grouped as "p_img".',
    ppt_tip_3: 'Images export as placeholders, replace manually from assets.',
    ppt_tip_4: '1920x1080 frame = PPT 16:9. Scale 0.5x recommended.',
    ppt_tip_5: 'Reset only affects plugin. Use Ctrl+Z to undo changes.',
    ppt_btn_auto: '🚀 Auto Export PPT',
    ppt_btn_manual: '📦 Manual Download',
    ppt_btn_reset: '🌀 Reset',
    ppt_step1_t: '1. Global Clean',
    ppt_step1_d: 'Unlock layers, remove hidden, unbind instances',
    ppt_step2_t: '2. Rasterize Icons',
    ppt_step2_d: 'Convert complex vectors and p_img to PNG',
    ppt_step3_t: '3. Deep Flatten',
    ppt_step3_d: 'Remove all groups and invisible frames',
    ppt_step4_t: '4. Generate PPT',
    ppt_step4_d: 'Extract layout and generate .pptx',
    ppt_step4_scale: 'Scale to 960x540 (recommended)',
    ppt_step5_t: '5. Export Assets',
    ppt_step5_d: 'Package PPT and images (.zip)',
    ppt_step6_t: 'Complete',
    ppt_step6_d: 'Files ready for download',
    ppt_stat_wait: 'Waiting',
    ppt_stat_done: '✅ Done',
    ppt_btn_next: 'Next →',
    ppt_btn_done: 'Completed',
    ppt_btn_run: 'Run STEP ',
    ppt_confirm_auto: '⚠️ Auto export?\nMake sure you are on a COPY page with frames selected.',
    ppt_confirm_reset: 'Reset progress?',
    ppt_no_data: 'No data',
    ppt_loading_analyze: 'Analyzing design structure...',
    ppt_loading_parse: 'Large files take time, please wait...',
  }
};
